# Generated by Django 5.2.4 on 2025-09-02 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the client making the request')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the request was made')),
                ('path', models.CharField(help_text='Request path/URL', max_length=500)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
